export const data = [
  {
    id: '1',
    name: 'Molhos',
    title: 'Escolha os molhos',
    internal_name: 'molhos',
    type: 'multi',
    price: 15,
    products: [
      {
        id: '1',
        category_id: '1',
        name: 'Burger supreme',
        internal_name: 'BG_SUP',
        image_url: '',
        description:
          'Hamburguer, pão brioche, cheddar , tomate, pickles, salada, maionese de ervas',
        cost_price: 9.85,
        price: 15.0,
        margin: 100.0,
        product_unity: 'unity',
        product_type: 'Simples',
        is_active: true,
        default_quantity: 1,
        max_quantity: 10,
        calories: 670,
        barcode: 8501000000035,
        internal_barcode: 13345,
        item_stock_quantity: 100,
        badges: ['eggs', 'nuts'],
        direct_sale: true,
        display_featured: false,
        display_new_item: true,
      },
    ],
  },
  {
    id: '2',
    name: 'Ponto da carne',
    title: 'Escolha os molhos',
    internal_name: 'molhos',
    type: 'single',
    price: 15,
    products: [],
  },
];
