export default [
  {
    key: 'lactose',
    label: 'Lactose',
    value: 'L',
    color: 'hsla(38, 90%, 68%, 1)',
  },
  {
    key: 'lactose_free',
    label: 'Sem Lactose',
    value: 'LF',
    color: 'hsla(50, 90%, 70%, 1)',
  },
  {
    key: 'vegan',
    label: 'Vegano',
    value: 'Vegano',
    color: 'hsla(97, 50%, 48%, 1)',
  },
  {
    key: 'vegetarian',
    label: 'Vegetariano',
    value: 'V',
    color: 'hsla(80, 40%, 60%, 1)',
  },
  {
    key: 'chef',
    label: 'Do Chef',
    value: 'Chef',
    color: 'hsla(8, 90%, 66%, 0.94)',
  },
  { key: 'eggs', label: 'Ovo', value: 'Ovo', color: 'hsla(50, 70%, 80%, 1)' },
  {
    key: 'gluten',
    label: 'Glúten',
    value: 'G',
    color: 'hsl(17, 50%, 88%, 1)',
  },
  {
    key: 'gluten_free',
    label: 'Sem Glúten',
    value: 'GF',
    color: 'hsl(17, 50%, 70%, 1)',
  },
  {
    key: 'healthy',
    label: 'Saudável',
    value: 'CS',
    color: 'hsl(172, 42%, 52%)',
  },
  {
    key: 'fish',
    label: 'Peixe',
    value: 'Peixe',
    color: 'hsl(207, 11%, 65%)',
  },
  {
    key: 'seafood',
    label: 'Frutos do mar',
    value: 'FM',
    color: 'hsla(200, 62%, 50%, 1)',
  },
  {
    key: 'spicy',
    label: 'Pimenta',
    value: 'Hot',
    color: 'hsla(1, 90%, 55%, 0.94)',
  },
  {
    key: 'nuts',
    label: 'Nozes',
    value: 'Nozes',
    color: 'hsla(1, 20%, 50%, 0.94)',
  },
  {
    key: 'organic',
    label: 'Orgânico',
    value: 'O',
    color: 'hsla(3, 15%, 30%, 0.94)',
  },
  { key: 'raw', label: 'Cru', value: 'Cru', color: 'hsl(207, 11%, 65%)' },
  {
    key: 'soja',
    label: 'Soja',
    value: 'Soja',
    color: 'purple',
  },
  {
    key: 'wheat',
    label: 'Trigo',
    value: 'Trigo',
    color: 'hsla(50, 30%, 70%, 1)',
  },
];
