export const data = [
  {
    id: '1',
    category_id: '1',
    name: 'Burger supreme',
    internal_name: 'BG_SUP',
    image_url: '',
    description:
      'Hamburguer, pão brioche, cheddar , tomate, pickles, salada, maionese de ervas',
    cost_price: 9.85,
    price: 15.0,
    margin: 100.0,
    product_unity: 'unity',
    isActive: true,
    default_quantity: 1,
    max_quantity: 10,
    calories: 670,
    barcode: 8501000000035,
    internal_barcode: 13345,
    item_stock_quantity: 100,
    badges: ['eggs', 'nuts'],
    direct_sale: true,
    display_featured: false,
    display_new_item: true,
  },
  {
    id: '2',
    category_id: '1',
    name: 'Cheeseburger de pinhão da Dona Cleide jdisajdi dusaiudisudisauidsu ',
    internal_name: 'BG_SUP',
    image_url: '',
    description:
      'Hamburguer, pão brioche, cheddar, tomate, pickles, salada, maionese de ervas, tomate, pickles, salada, maionese de ervas',
    cost_price: 9.85,
    price: 15.0,
    margin: 100.0,
    product_unity: 'unity',
    isActive: true,
    default_quantity: 1,
    max_quantity: 10,
    calories: 670,
    barcode: 8501000000035,
    internal_barcode: 13345,
    item_stock_quantity: 100,
    badges: ['eggs', 'nuts', 'vegan', 'vegetarian', 'gluten'],
    direct_sale: true,
    display_featured: false,
    display_new_item: false,
  },
  {
    id: '3',
    category_id: '1',
    name: 'Cheeseburger de pinhão',
    internal_name: 'BG_SUP',
    image_url: '',
    description:
      'Hamburguer, pão brioche, cheddar, tomate, pickles, salada, maionese de ervas, tomate, pickles, salada, maionese de ervas',
    cost_price: 9.85,
    price: 15.0,
    margin: 100.0,
    product_unity: 'unity',
    isActive: true,
    default_quantity: 1,
    max_quantity: 10,
    calories: 670,
    barcode: 8501000000035,
    internal_barcode: 13345,
    item_stock_quantity: 100,
    badges: ['eggs', 'nuts', 'vegan', 'vegetarian'],
    direct_sale: true,
    display_featured: true,
    display_new_item: true,
  },
];
